[package]
name = "steg"
version = "0.1.0"
edition = "2021"
description = "Embed an image within another image."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
